package com.framework.pages;

import com.microsoft.playwright.Page;

/*
 * public class DashboardPage {
 * 
 * private Page page;
 * 
 * public DashboardPage(Page page) { this.page = page; }
 * 
 * private String dashBoardTitle = "//h6[contains(@class,'oxd-topbar-header')]";
 * 
 * 
 * 
 * }
 */

import com.microsoft.playwright.Locator;

import lombok.Getter;

@Getter  // Lombok will generate getters for all non-static fields
public class DashboardPage {

    private final Page page;
    
    // Locator fields (getters auto-generated by Lombok)
    private final Locator dashboardTitle;

    // Locator strings as constants
    private static final String DASHBOARD_TITLE = "//h6[contains(@class,'oxd-topbar-header')]";

    public DashboardPage(Page page) {
        this.page = page;
        this.dashboardTitle = page.locator(DASHBOARD_TITLE);
    }

}