package com.framework.pages;

import com.microsoft.playwright.Page;
import com.microsoft.playwright.Locator;

import lombok.Getter;

@Getter // Lombok will generate getters for all non-static fields
public class DashboardPage {

	private final Page page;

	// Locator fields (getters auto-generated by Lombok)
	private final Locator dashboardTitle;
	private final Locator leftMenuItems;
	private final Locator dropdownMenu;
	private final Locator dropdownMenuList;

	// Locator strings as constants
	private static final String DASHBOARD_TITLE = "//h6[contains(@class,'oxd-topbar-header')]";
	private static final String LEFT_MENU_ITEMS = ".oxd-main-menu li a span";
	private static final String DROPDOWN_MENU = ".oxd-userdropdown-tab i";
	private static final String DROPDOWN_LIST = ".oxd-dropdown-menu li a";

	public DashboardPage(Page page) {
		this.page = page;
		this.dashboardTitle = page.locator(DASHBOARD_TITLE);
		this.leftMenuItems = page.locator(LEFT_MENU_ITEMS);
		this.dropdownMenu = page.locator(DROPDOWN_MENU);
		this.dropdownMenuList = page.locator(DROPDOWN_LIST);
	}

}